'use client'

import { Card, CardHeader, CardTitle, CardDescription } from "@/components/ui/card"
import { RepoLanguageChart } from '@/components/RepoLanguageChart'

const projects = [
  {
    title: "Moodify",
    description: [`Moodify is a platform that allows users to re-live their memories through music.`, `By uploading an image,
        the user will be prompted with 10 songs that best match the emotion of the photo.
        The user can then listen to the songs and reminisce about the good times.`, 
        `This project was built in 36 hours at LA Hacks 24. It aims to provide better music recommendations for stories than what Instagram can offer currently.`, 
        `The project received decent feedbacks from the judges at the Hackathon.`],
    tags: ["Hackathon", "Full Stack Development", "Google Gemini Vision Pro"],
    links: [
      { label: "GitHub", url: "https://github.com/THL-Leo/Moodify" },
    ],
    github: {
      owner: "THL-Leo",
      repo: "Moodify"
    }
  },
  {
    title: "Brainrot Personality Test",
    description: [
        `Received 'Would Blow up on TikTok' award at jia.seed Hackathon 24.`,
        `This project is a personality test on what kind of brainrot content the user knows.`,
        `It utilizes OpenAI's GPT-4o mini model to analyze the user's response and roast them for the time they spend on social media.`,
        `This project was built in 24 hours.`,
    ],
    tags: ["Hackathon", "Full Stack Development", "OpenAI"],
    links: [
      { label: "GitHub", url: "https://github.com/THL-Leo/brnrot.ai" },
      { label: "Live Demo", url: "https://brnrot-ai.vercel.app/" },
    ],
    github: {
      owner: "THL-Leo",
      repo: "brnrot.ai"
    }
  },
  {
    title: "Email Writer",
    description: [
        `Email Writer is a tool that allows Claude to analyze the way user writes their emails and generate one based on their prompt.`,
        `It is built using Next.js, Shadcn, and Claude API.`,
        `It was built using a clear roadmap generated by Claude and adheres to feature by feature development instead of one shot development.`,
        `This was built in 12 hours at Anthropic x USC Hackathon 25.`
    ],
    tags: ["Hackathon", "Full Stack Development", "Claude"],
    links: [
      { label: "GitHub", url: "https://github.com/THL-Leo/idontknowhowtowriteemails" },
    ],
    github: {
      owner: "THL-Leo",
      repo: "idontknowhowtowriteemails"
    }
  }
  // Add more projects as needed
]

export function ProjectsSection() {
  return (
    <section className="py-20 px-4 md:px-8 lg:px-16" id="projects">
      <div className="max-w-6xl mx-auto">
        {projects.map((project, index) => (
          <div key={project.title} className="mb-32 last:mb-0">
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-12">
              {/* Left Column */}
              <div className="space-y-6">
                <h2 className="text-xl font-bold">
                  {project.title}
                </h2>
                <div className="space-y-4">
                  {project.description.map((desc, idx) => (
                    <p 
                      className="text-base" 
                      key={project.title + idx}
                    >
                      {desc}
                    </p>
                  ))}
                </div>
                {/* Tags */}
                <div className="flex flex-wrap gap-2">
                  {project.tags.map((tag) => (
                    <span
                      key={tag}
                      className="px-3 py-1 bg-muted rounded-full text-sm"
                    >
                      {tag}
                    </span>
                  ))}
                </div>

                {/* Links */}
                <div className="space-x-4 pt-2">
                  {project.links.map((link) => (
                    <a
                      key={link.label}
                      href={link.url}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="text-foreground hover:text-muted-foreground transition-colors"
                    >
                      {link.label} →
                    </a>
                  ))}
                </div>
              </div>

              {/* Right Column - Chart */}
              <div>
                <RepoLanguageChart 
                  repoName={project.github.repo} 
                />
              </div>
            </div>
          </div>
        ))}
      </div>
    </section>
  )
} 